name: 1. add-chart-card
label: '[Page] [Chart] - Add chart card to page'
description: Allow to add a chart card to a page
group: '[Page] [Chart] - Add'

variables:
  - name: url
    label: Page url
    default_value: /dashboard
  - name: title
    label: Title
    default_value: Performance
  - name: subtitle
    label: Subtitle
    default_value: Comparison between Sales and Profit

rules:
  - name: add-chart-initial-data
    target: ../../../../../app{{url}}/data/chart/chart.ts
  - name: add-chart-component
    target: ../../../../../app{{url}}/cards/chart.tsx
  - name: add-chart-to-page
    target: ../../../../../app{{url}}/page.tsx